# Container-DotNet-App application

trigger:
- master
- hotfix/*

variables:
  domainId: dfpg
  containerAppProjectPath: BerkeleysMocking\BerkeleysMocking.csproj
  containerRegistryRepository: berkeleys-mock

name: 1.0.$(Date:yy)$(DayOfYear)$(Rev:.r)

resources:
  repositories:
  - repository: templates
    type: git
    name: DFDevOps\cicd-templates
    ref: refs/tags/stable-1
    # http://tdc1tfsapp01:8080/tfs/DefaultCollection/DFDevOps/_git/cicd-templates

jobs:
- job: Build
  pool:
    demands: DotNetFramework
  workspace:
    clean: all
  variables:
  - template: ci/variables.yml@templates

  steps:
  - template: ci/set-branch-build-number.yml@templates

  - template: ci/build-and-test.yml@templates
    parameters:
      withCoverage: false

  - template: ci/docker-build-push-all-tags.yml@templates
    parameters:
      containerRegistryNamespace: $(domainId)
      apps:
      - projectPath: $(containerAppProjectPath)
        containerRegistryRepository: $(containerRegistryRepository)

  - template: ci/symbols-publish.yml@templates

  - template: ci/sonar-qube-publish.yml@templates