version: '3.4'

services:
  webui:
    image: mockbank/app:1.0
    build:
      context: .
      dockerfile: src/presentation/MockBank.WebApi/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "UseInMemoryDatabase=false"
      - "ConnectionStrings__DefaultConnection=Data Source=MockBankDatabaseProduction.sqlite3;Mode=ReadWriteCreate;"
      - "IdentityServer__Key__Type=Development"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=madison"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx"
    volumes:
       - ~/conf.d/https:/https/
      # - /tmp/data:/app
    ports:
      - "5000:5000"
      - "5001:5001"
